config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations:  'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/login', to: 'users/sessions#new'
    get '/register', to: 'users/registrations#new'
    delete '/logout', to: 'users/sessions#destroy'
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :amazon_products, only: %i[index show], path: 'products'
  resources :amazon_product_categories, only: %i[index show], path: 'categories' do
    resources :amazon_products, only: [:show], path: 'products'
  end
  resources :amazon_product_groups, only: %i[index show], path: 'groups' do
    resources :amazon_products, only: [:show], path: 'products'
  end

  post '/search', to: 'pages#search'
  get '/results', to: 'pages#results'
  get '/popular', to: 'pages#popular'
  get '/largest-savings', to: 'pages#largest_savings'

  get '/profile', to: 'users#show'
  get '/watch-list', to: 'users#watch_list'

  root to: 'pages#home'
end

app/models/amazon_product_group.rb
# frozen_string_literal: true

class AmazonProductGroup < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :amazon_products

  scope :alphabetical, -> { order('name ASC') }
end

app/controllers/amazon_product_groups_controller.rb
# frozen_string_literal: true

class AmazonProductGroupsController < ApplicationController
  before_action :set_amazon_product_group, only: [:show]

  def index
    @amazon_product_groups = AmazonProductGroup.alphabetical
    prepare_meta_tags(title: 'Groups', reverse: true)
  end

  def show
    prepare_meta_tags(title: helpers.friendly_name(@amazon_product_group.name), reverse: true)
  end

  private

  def set_amazon_product_group
    @amazon_product_group = AmazonProductGroup.friendly.find(params[:id])
  end
end

app/views/amazon_product_groups/index.html.erb
<div>
  <h1>Groups</h1>
  <% @amazon_product_groups.each do |p| %>
    <%= link_to friendly_name(p.name), amazon_product_group_path(p) %><br>
  <% end %>
</div>

app/views/amazon_product_groups/show.html.erb
<h1><%= @amazon_product_group.name %></h1>

<div>
  <h2>Products</h2>
  <% @amazon_product_group.amazon_products.each do |p| %>
    <%= link_to p.title, amazon_product_group_amazon_product_path(amazon_product_group_id: @amazon_product_group, id: p) %><br>
  <% end %>
</div>