config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations:  'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/login', to: 'users/sessions#new'
    get '/register', to: 'users/registrations#new'
    delete '/logout', to: 'users/sessions#destroy'
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :amazon_products, only: %i[index show], path: 'products'
  resources :amazon_product_categories, only: %i[index show], path: 'categories' do
    resources :amazon_products, only: [:show], path: 'products'
  end
  resources :amazon_product_groups, only: %i[index show], path: 'groups' do
    resources :amazon_products, only: [:show], path: 'products'
  end

  post '/search', to: 'pages#search'
  get '/results', to: 'pages#results'
  get '/popular', to: 'pages#popular'
  get '/largest-savings', to: 'pages#largest_savings'

  get '/profile', to: 'users#show'
  get '/watch-list', to: 'users#watch_list'

  root to: 'pages#home'
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <i class="close icon"></i>
    <div class="header">
      <%= key.camelize %>
    </div>
    <%= value %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="ui vertical footer segment">
  <div class="ui center aligned container">
    <img src="" class="ui centered mini image">
    <div class="ui horizontal small divided link list">
      <a class="item" href="#">Site Map</a>
      <a class="item" href="#">Contact Us</a>
      <a class="item" href="#">Terms and Conditions</a>
      <a class="item" href="#">Privacy Policy</a>
      <a class="item" href="https://twitter.com/traqker" target="_blank">Twitter</a>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="ui stackable menu">
  <div class="ui container">
      <%= link_to "/", class: "item" do %>
        <%= image_tag("logo.png") %>
      <% end %>
    <%= active_link_to "Products", amazon_products_path, class: "ui item" %>
    <div class="right menu">
      <div class="item">
        <div class="ui icon input">
          <%= form_tag search_path, style: "width: 100%;" do %>
            <%= text_field_tag :query, params[:query], style: "width: 100%;", placeholder: "Search..." %>
          <% end %>
          <i class="search link icon"></i>
        </div>
      </div>
    </div>
    <% if user_signed_in? %>
      <%= active_link_to "Profile", "/profile", class: "ui item" %>
      <%= active_link_to "Watch List", "/watch-list", class: "ui item" %>
      <%= link_to "Logout", "/logout", method: "delete", class: "ui item" %>
    <% else %>
      <%= active_link_to "Login", "/login", class: "ui item" %>
      <%= active_link_to "Register", "/register", class: "ui item" %>
    <% end %>
  </div>
</div>

app/views/shared/_spark_line_graph.html.erb
<% data = product.amazon_product_histories.group_by_day(:created_at, format: "%b %-d", series: false).minimum(:price) %>

<canvas id="<%= id %>" width="100" height="50"></canvas>

<script>
$(document).ready(function() {
  var ctx = document.getElementById("<%= id %>").getContext("2d");
  var scatterChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels : <%= raw data.keys %>,
        datasets : [
          {
            fill: true,
            lineTension: 0,
            backgroundColor: "rgba(75,192,192,0.4)",
            borderColor: "rgba(75,192,192,1)",
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: "rgba(75,192,192,1)",
            pointBackgroundColor: "#fff",
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "rgba(75,192,192,1)",
            pointHoverBorderColor: "rgba(220,220,220,1)",
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data: <%= raw data.values %>,
            spanGaps: false,
          }
        ]
      },
      options: {
        responsive: false,
        animation : false,
        scales: {
          xAxes: [{
            display: false,
            gridLines: {
              display: false
            }
          }],
          yAxes: [{
            display: false,
            gridLines: {
              display: false
            }
          }]
        }
      }
  })
});
</script>