config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations:  'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/login', to: 'users/sessions#new'
    get '/register', to: 'users/registrations#new'
    delete '/logout', to: 'users/sessions#destroy'
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :amazon_products, only: %i[index show], path: 'products'
  resources :amazon_product_categories, only: %i[index show], path: 'categories' do
    resources :amazon_products, only: [:show], path: 'products'
  end
  resources :amazon_product_groups, only: %i[index show], path: 'groups' do
    resources :amazon_products, only: [:show], path: 'products'
  end

  post '/search', to: 'pages#search'
  get '/results', to: 'pages#results'
  get '/popular', to: 'pages#popular'
  get '/largest-savings', to: 'pages#largest_savings'

  get '/profile', to: 'users#show'
  get '/watch-list', to: 'users#watch_list'

  root to: 'pages#home'
end

app/views/pages/_statistics.html.erb
<div class="ui statistics">
  <div class="statistic">
    <div class="value">
      <%= number_to_currency(AmazonProduct.total_savings, precision: 0) %>
    </div>
    <div class="label">
      Savings
    </div>
  </div>
  <div class="statistic">
    <div class="value">
      <%= AmazonProduct.count %>
    </div>
    <div class="label">
      Products
    </div>
  </div>
  <div class="statistic">
    <div class="value">
      <%= AmazonProductHistory.count %>
    </div>
    <div class="label">
      Prices tracked
    </div>
  </div>
  <div class="statistic">
    <div class="value">
      <%= User.count %>
    </div>
    <div class="label">
      Members
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="ui one column grid">
  <div class="row">
    <div class="column">
      <%= render 'shared/flash_messages' %>
      <%= form_tag search_path do %>
        <div class="ui inverted segment">
          <div class="ui inverted left icon input full-width big">
            <%= text_field_tag :query, nil, placeholder: 'Enter Amazon URL, ASIN or search by keywords...' %>
            <i class="search icon"></i>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="column">
      <div class="ui compact menu">
        <a class="item active" href="/popular">
          Popular
        </a>
        <a class="item" href="/largest-savings">
          Largest savings
        </a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="column">
      <div class="ui four column grid stackable">
        <% @amazon_products.each do |product| %>
          <div class="column">
            <div class="ui fluid card link">
              <a class="image" href="<%= amazon_product_path(product) %>" style="background: #fff; min-height: 150px;">
                <img class="ui fluid image center" src="<%= image_path(product.presenter.main_image) %>" style="max-height: 150px;width: auto;">
              </a>
              <div class="content">
                <a class="header dotdotdot" href="<%= amazon_product_path(product) %>"><%= product.title %></a>
                <div class="meta">
                  <a href="<%= amazon_product_group_path(product.amazon_product_group) %>"><%= friendly_name(product.amazon_product_group.name) %></a>
                </div>
              </div>
              <% if product.current_price%>
                <div class="extra content">
                  <span>
                    <span class="current_price_small">Price:</span>
                    <span class="current_price"><%= number_to_currency(product.presenter.price) %></span>
                    <% if product.current_prime %>
                      <i class="a-icon a-icon-prime"></i>
                    <% end %>
                  </span>
                  <div><strike><%= number_to_currency(product.presenter.maximum_price) %></strike> Save: <%= number_to_currency(product.presenter.amount_saved) %> (<%= product.percentage_to_save %>%)</div>
                </div>
              <% else %>
                <div class="extra content">
                  <p>No prices yet</p>
                </div>
              <% end %>
              <div class="ui two column attached buttons">
                <a class="ui green button" href="<%= product.detail_page_url %>" target="_blank">
                  <i class="shop icon"></i>Buy
                </a>
                <a class="ui yellow button" href="<%= amazon_product_path(product) %>">
                  <i class="unhide icon"></i>View
                </a>
              </div>
            </div>
          </div>
        <% end %>
        <%= paginate @amazon_products %>
      </div>
    </div>
  </div>
</div>

app/views/pages/largest_savings.html.erb
<div class="ui one column grid">
  <div class="row">
    <div class="column">
      <%= render 'shared/flash_messages' %>
      <%= form_tag search_path do %>
        <div class="ui inverted segment">
          <div class="ui inverted left icon input full-width big">
            <%= text_field_tag :query, nil, placeholder: 'Enter Amazon URL, ASIN or search by keywords...' %>
            <i class="search icon"></i>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="column">
      <div class="ui compact menu">
        <a class="link item" href="/popular">
          Popular
        </a>
        <a class="item active" href="/largest-savings">
          Largest savings
        </a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="column">
      <div class="ui four column grid stackable">
        <% @amazon_products.each do |product| %>
          <div class="column">
            <div class="ui fluid card link">
              <a class="image" href="<%= amazon_product_path(product) %>" style="background: #fff; min-height: 150px;">
                <img class="ui fluid image center" src="<%= image_path(product.presenter.main_image) %>" style="max-height: 150px;width: auto;">
              </a>
              <div class="content">
                <a class="header dotdotdot" href="<%= amazon_product_path(product) %>"><%= product.title %></a>
                <div class="meta">
                  <a href="<%= amazon_product_group_path(product.amazon_product_group) %>"><%= friendly_name(product.amazon_product_group.name) %></a>
                </div>
              </div>
              <% if product.current_price%>
                <div class="extra content">
                  <span>
                    <span class="current_price_small">Price:</span>
                    <span class="current_price"><%= number_to_currency(product.presenter.price) %></span>
                    <% if product.current_prime %>
                      <i class="a-icon a-icon-prime"></i>
                    <% end %>
                  </span>
                  <div><strike><%= number_to_currency(product.presenter.maximum_price) %></strike> Save: <%= number_to_currency(product.presenter.amount_saved) %> (<%= product.percentage_to_save %>%)</div>
                </div>
              <% else %>
                <div class="extra content">
                  <p>No prices yet</p>
                </div>
              <% end %>
              <div class="ui two column attached buttons">
                <a class="ui green button" href="<%= product.detail_page_url %>" target="_blank">
                  <i class="shop icon"></i>Buy
                </a>
                <a class="ui yellow button" href="<%= amazon_product_path(product) %>">
                  <i class="unhide icon"></i>View
                </a>
              </div>
            </div>
          </div>
        <% end %>
        <%= paginate @amazon_products %>
      </div>
    </div>
  </div>
</div>

app/views/pages/popular.html.erb
<div class="ui one column grid">
  <div class="row">
    <div class="column">
      <%= render 'shared/flash_messages' %>
      <%= form_tag search_path do %>
        <div class="ui inverted segment">
          <div class="ui inverted left icon input full-width big">
            <%= text_field_tag :query, nil, placeholder: 'Enter Amazon URL, ASIN or search by keywords...' %>
            <i class="search icon"></i>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="column">
      <div class="ui compact menu">
        <a class="item active" href="/popular">
          Popular
        </a>
        <a class="item" href="/largest-savings">
          Largest savings
        </a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="column">
      <div class="ui four column grid stackable">
        <% @amazon_products.each do |product| %>
          <div class="column">
            <div class="ui fluid card link">
              <a class="image" href="<%= amazon_product_path(product) %>" style="background: #fff; min-height: 150px;">
                <img class="ui fluid image center" src="<%= image_path(product.presenter.main_image) %>" style="max-height: 150px;width: auto;">
              </a>
              <div class="content">
                <a class="header dotdotdot" href="<%= amazon_product_path(product) %>"><%= product.title %></a>
                <div class="meta">
                  <a href="<%= amazon_product_group_path(product.amazon_product_group) %>"><%= friendly_name(product.amazon_product_group.name) %></a>
                </div>
              </div>
              <% if product.current_price%>
                <div class="extra content">
                  <span>
                    <span class="current_price_small">Price:</span>
                    <span class="current_price"><%= number_to_currency(product.presenter.price) %></span>
                    <% if product.current_prime %>
                      <i class="a-icon a-icon-prime"></i>
                    <% end %>
                  </span>
                  <div><strike><%= number_to_currency(product.presenter.maximum_price) %></strike> Save: <%= number_to_currency(product.presenter.amount_saved) %> (<%= product.percentage_to_save %>%)</div>
                </div>
              <% else %>
                <div class="extra content">
                  <p>No prices yet</p>
                </div>
              <% end %>
              <div class="ui two column attached buttons">
                <a class="ui green button" href="<%= product.detail_page_url %>" target="_blank">
                  <i class="shop icon"></i>Buy
                </a>
                <a class="ui yellow button" href="<%= amazon_product_path(product) %>">
                  <i class="unhide icon"></i>View
                </a>
              </div>
            </div>
          </div>
        <% end %>
        <%= paginate @amazon_products %>
      </div>
    </div>
  </div>
</div>

app/views/pages/results.html.erb
<style>
  .item {
    position:relative;
  }
  .graph {
    position:absolute;
    bottom:0;
    right:0;
    z-index: -1;
  }
</style>
<script>
  Chart.defaults.global.legend.display = false;
  Chart.defaults.global.tooltips.enabled = false;
</script>

<h1>Products</h1>

<div>
  <div class="ui divided items">
  <% @amazon_products.each do |product| %>
    <div class="item">
      <div class="ui small image">
        <a href="<%= amazon_product_path(product) %>">
          <img src="<%= image_path(product.presenter.main_image) %>">
        </a>
      </div>
      <div class="content">
        <a class="header"><%= link_to product.title.truncate(60), amazon_product_path(product) %></a>
        <div class="description">
          <p><%= product.features.first %></p>
        </div>
        <% if product.current_price%>
          <div class="extra content">
            <span>
              <span class="current_price_small">Price:</span>
              <span class="current_price"><%= number_to_currency(product.presenter.price) %></span>
              <% if product.current_prime %>
                <i class="a-icon a-icon-prime"></i>
              <% end %>
            </span>
            <div><strike><%= number_to_currency(product.presenter.maximum_price) %></strike> Save: <%= number_to_currency(product.presenter.amount_saved) %> (<%= product.percentage_to_save %>%)</div>
          </div>
        <% end %>
        <div class="extra">
          <% product.tags.each do |tag| %>
            <div class="ui label"><i class="tag icon"></i> <%= tag %></div>
          <% end %>
        </div>
        <div class="graph">
          <%= render partial: 'shared/spark_line_graph',
                      locals: { id: "sparkey_#{product.id}",
                                product: product } %>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate @amazon_products %>
  </div>
</div>